# Generated by Django 4.0.5 on 2022-07-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_product_orderitem_product_checkoutaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='datetime_ofpayment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_delivered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_received',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_signature',
        ),
        migrations.RemoveField(
            model_name='order',
            name='start_date',
        ),
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='CheckoutAddress',
        ),
    ]
